<?php 


/**
 * Implements hook_init().
 */
function betgame_init() {
  module_load_include('php', 'betgame', 'lib/Entity');
  module_load_include('php', 'betgame', 'lib/EntityDao');
}


/**
 * Implements hook_menu().
 */
function betgame_menu() {
  $items = array();

  $items['admin/config/betgame'] = array(
    'title' => 'Betgame',
    'description' => 'Administer betgames',
    'position' => 'right',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'page arguments' => array(),
    'access arguments' => array('administer betgame'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system')
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function betgame_permission() {
  return array(
    'access betgame' => array(
      'title' => t('Access bet games'),
      'description' => t(''),
    ),
    'administer betgame' => array(
      'title' => t('Administer bet games'),
      'description' => t(''),
    ),
  );
}