<?php 

/*
 * API to create generic tournament matchplans.
 * 
 * Currently it only offers a programatically interface to create a matchplan - 
 * see implemented update hooks.
 */

/**
 * Implements hook_init().
 */
function tippgame_matchplan_init() {
  module_load_include('php', 'tippgame_matchplan', 'lib/MatchPlanEntity');
}

function tippgame_matchplan_dao() {
  module_load_include('php', 'tippgame_matchplan', 'lib/MatchPlanDao');
  
  $cache = &drupal_static(__FUNCTION__, array());
  if(!isset($cache['Dao'])) {
    $cache['Dao'] = new MatchPlanDao();
  }
  return $cache['Dao'];
}

/**
 * Implements hook_menu().
 * 
 */
function tippgame_matchplan_menu() {
  $items = array();

  $items['admin/config/tippgame/matchplan'] = array(
    'title' => 'Matchplan Admin',
    'description' => '',
    'page callback' => 'tippgame_matchplan_page',
    'page arguments' => array(),
    'access arguments' => array('administer matchplan'),
    'file' => 'tippgame_matchplan.admin.inc',
  );
  
  // currently not supported
  /* 
  $items['admin/config/tippgame/matchplan/add'] = array(
    'title' => 'Add Matchplan',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tippgame_matchplan_edit_form'),
    'access arguments' => array('administer matchplan'),
    'file' => 'tippgame_matchplan.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  
  $items['admin/config/tippgame/matchplan/%matchplan/edit'] = array(
    'title' => 'Matchplan Admin',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tippgame_matchplan_edit_form', 4),
    'access arguments' => array('administer matchplan'),
    'file' => 'tippgame_matchplan.admin.inc',
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  */

  return $items;
}

/**
 * Loader for menu placeholder.
 *
 * @param integer $id
 *
 * @return Matchplan or NULL
 */
function matchplan_load($id) {
  return tippgame_matchplan_dao()->findMatchPlan($id);
}

/**
 * Implements hook_theme().
 */
function tippgame_matchplan_theme($existing, $type, $theme, $path) {
  return array(
    'tippgame_matchplan_admin_form_fixtures' => array(
      'render element' => 'fixtures',
      'file' => 'tippgame_matchplan.admin.inc',
    )
  );
}

/**
 * Implements hook_permission().
 */
function tippgame_matchplan_permission() {
   return array(
    'administer matchplan' => array(
      'title' => t('Administer Matchplan'), 
      'description' => t(''),
    ),
  );
}

function _tippgame_matchplan_select_matchplan() {
  $cache = &drupal_static(__FUNCTION__, array());
  if(!isset($cache['matchplans'])) {
    $plans = tippgame_matchplan_dao()->findMatchPlans();
    foreach($plans as $p) {
      $cache['matchplans'][$p->getId()] = $p->getName();
    }
  }
  return $cache['matchplans'];

}
