<?php 


/**
 * Implements hook_init().
 */
function betgame_competition_init() {
  module_load_include('php', 'betgame_competition', 'lib/CompetitionEntity');

}

function betgame_competition_dao() {
  module_load_include('php', 'betgame_competition', 'lib/CompetitionDao');

  $cache = &drupal_static(__FUNCTION__, array());
  if(!isset($cache['Dao'])) {
    $cache['Dao'] = new CompetitionDao();
  }
  return $cache['Dao'];
}

function betgame_competition_controller() {
  module_load_include('php', 'betgame_competition', 'lib/CompetitionController');

  $cache = &drupal_static(__FUNCTION__, array());
  if(!isset($cache['Controller'])) {
    $cache['Controller'] = new CompetitionController();
    $cache['Controller']->setCompetitionDao(betgame_competition_dao());
    $cache['Controller']->setMatchplanDao(betgame_matchplan_dao());
  }
  return $cache['Controller'];
}

/**
 * Implements hook_menu().
 */
function betgame_competition_menu() {
  $items = array();

  $path_pages = drupal_get_path('module', 'betgame_competition') . '/pages';
  $path_admin = drupal_get_path('module', 'betgame_competition') . '/admin';
  
  $items['betgame/competition/%competition'] = array(
    'title callback' => '_betgame_competition_page_competition_title',
    'title arguments' => array(2),
    'description' => '',
    'page callback' => 'betgame_competition_page_competition',
    'page arguments' => array(2),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.pages.inc',
    'file path' => $path_pages,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['betgame/competition/%competition/admin'] = array(
    'title' => 'Admin',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competitions_form'),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_LOCAL_ACTION,
  );
  
  // admin
  
  $items['admin/config/betgame/competition'] = array(
    'title' => 'Competitions',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competitions_form'),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.admin.inc',
    'file path' => $path_admin,
  );
  $items['admin/config/betgame/competition/add'] = array(
    'title' => 'Add Competition',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_edit_form'),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_LOCAL_ACTION | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/betgame/competition/%competition/edit'] = array(
    'title' => 'Edit Competition',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_edit_form', 4),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/betgame/competition/%competition/delete'] = array(
    'title' => 'Delete Competition',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_delete_form', 4),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );

  // GROUP
  $items['admin/config/betgame/competition/%competition/group'] = array(
    'title' => 'Groups',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_groups_form', 4),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.group.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/betgame/competition/%competition/group/add'] = array(
    'title' => 'Add Group',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_group_edit_form', 4),
    'access callback' => '_betgame_competition_access_add_group',
    'access arguments' => array(4),
    'file' => 'betgame_competition.group.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/betgame/competition/%competition/group/%group/edit'] = array(
    'title' => 'Edit Group',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_group_edit_form', 4, 6),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.group.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/betgame/competition/%competition/group/%group/delete'] = array(
    'title' => 'Delete Group',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_group_delete_form', 4, 6),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.group.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  
  // TEAM
  $items['admin/config/betgame/competition/%competition/team'] = array(
    'title' => 'Teams',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_teams_form', 4),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.team.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/betgame/competition/%competition/team/add'] = array(
    'title' => 'Add Team',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_team_edit_form', 4),
    'access callback' => '_betgame_competition_access_add_team',
    'access arguments' => array(4),
    'file' => 'betgame_competition.team.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/betgame/competition/%competition/team/%team/edit'] = array(
    'title' => 'Edit Team',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_team_edit_form', 4, 6),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.team.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/betgame/competition/%competition/team/%team/delete'] = array(
    'title' => 'Delete Team',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_team_delete_form', 4, 6),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.team.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  
  // GAMEDAY
  $items['admin/config/betgame/competition/%competition/gameday'] = array(
    'title' => 'Gamedays',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_gamedays_form', 4),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.gameday.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/betgame/competition/%competition/gameday/add'] = array(
    'title' => 'Add Gameday',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_gameday_edit_form', 4),
    'access callback' => '_betgame_competition_access_add_gameday',
    'access arguments' => array(4),
    'file' => 'betgame_competition.gameday.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/betgame/competition/%competition/gameday/%gameday/edit'] = array(
    'title' => 'Edit Gameday',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_gameday_edit_form', 4, 6),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.gameday.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/betgame/competition/%competition/gameday/%gameday/delete'] = array(
    'title' => 'Delete Gameday',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_gameday_delete_form', 4, 6),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.gameday.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  
  // MATCH
  $items['admin/config/betgame/competition/%competition/match'] = array(
    'title' => 'Matches',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_matchs_form', 4),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.match.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/betgame/competition/%competition/match/add'] = array(
    'title' => 'Add Match',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_match_edit_form', 4),
    'access callback' => '_betgame_competition_access_add_match',
    'access arguments' => array(4),
    'file' => 'betgame_competition.match.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/betgame/competition/%competition/match/generatefixtures'] = array(
    'title' => 'Generate matches',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_generatefixtures_form', 4),
    'access callback' => '_betgame_competition_access_generatefixtures',
    'access arguments' =>  array(4),
    'file' => 'betgame_competition.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/betgame/competition/%competition/match/%match/edit'] = array(
    'title' => 'Edit Match',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_match_edit_form', 4, 6),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.match.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/betgame/competition/%competition/match/%match/delete'] = array(
    'title' => 'Delete Match',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_match_delete_form', 4, 6),
    'access arguments' => array('administer betgame'),
    'file' => 'betgame_competition.match.admin.inc',
    'file path' => $path_admin,
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  
  // DEVEL_GENERATE
  $items['admin/config/development/generate/betgame'] = array(
    'title' => 'Generate betgames',
    'description' => 'Generate a given number of betgames.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('betgame_competition_devel_generate_content_form'),
    'access callback' => '_betgame_competition_access_devel',
    'access arguments' => array(),
    'file' => 'betgame_competition.devel_generate.inc',
  );
  
  
  return $items;
}

function _betgame_competition_access_devel() {
  return module_exists('devel_generate') && user_access('administer betgame');
}

function _betgame_competition_access_generatefixtures(Competition $competition) {
  return user_access('administer betgame')
  && betgame_competition_controller()->isReadyForFixtureGeneration($competition->getId());
}

function _betgame_competition_access_add_group(Competition $competition) {
  return user_access('administer betgame')
  && !betgame_competition_controller()->competitionGroupsComplete($competition->getId());
}

function _betgame_competition_access_add_team(Competition $competition) {
  return user_access('administer betgame')
  && !betgame_competition_controller()->competitionTeamsComplete($competition->getId());
}

function _betgame_competition_access_add_gameday(Competition $competition) {
  return user_access('administer betgame')
  && !betgame_competition_controller()->competitionGamedaysComplete($competition->getId());
}

function _betgame_competition_access_add_match(Competition $competition) {
  return FALSE;
  //user_access('administer betgame');
  //&& !betgame_competition_controller()->competitionGamedaysComplete($competition->getId());
}

/**
 * Loader for menu placeholder.
 *
 * @param integer $id
 *
 * @return Competition or NULL
 */
function competition_load($id) {
  return betgame_competition_dao()->findCompetition($id);
}

/**
 * Loader for menu placeholder.
 *
 * @param integer $id
 *
 * @return Team or NULL
 */
function team_load($id) {
  return betgame_competition_dao()->findTeam($id);
}

/**
 * Loader for menu placeholder.
 *
 * @param integer $id
 *
 * @return Group or NULL
 */
function group_load($id) {
  return betgame_competition_dao()->findGroup($id);
}

/**
 * Loader for menu placeholder.
 *
 * @param integer $id
 *
 * @return Gameday or NULL
 */
function gameday_load($id) {
  return betgame_competition_dao()->findGameday($id);
}

/**
 * Loader for menu placeholder.
 *
 * @param integer $id
 *
 * @return Match or NULL
 */
function match_load($id) {
  return betgame_competition_dao()->findMatch($id);
}

/**
 * Implements hook_theme().
 */
function betgame_competition_theme($existing, $type, $theme, $path) {
  $path_admin = drupal_get_path('module', 'betgame_competition') . '/admin';
  $path_page = drupal_get_path('module', 'betgame_competition') . '/pages';
  
  return array(
    'betgame_competition_matches' => array(
      'variables' => array('matches' => NULL, 'useShortnames' => FALSE, 'showHeader' => TRUE, 'cols' => array()),
      'file' => 'betgame_competition.pages.inc',
      'path' => $path_page,
    ),
    'betgame_competition_scoretable' => array(
      'variables' => array('tabledata' => NULL, 'useShortnames' => FALSE, 'showHeader' => TRUE),
      'file' => 'betgame_competition.pages.inc',
      'path' => $path_page,
    ),
    'betgame_competition_team' => array(
      'variables' => array('team' => NULL, 'useShortname' => FALSE),
      'file' => 'betgame_competition.pages.inc',
      'path' => $path_page,
    ),
    'betgame_competition_match_team' => array(
      'variables' => array('match' => NULL, 'type' => 'home', 'useShortname' => FALSE),
      'file' => 'betgame_competition.pages.inc',
      'path' => $path_page,
    ),
    'betgame_competition_team_placeholder' => array(
      'variables' => array('placeholder' => NULL, 'competition_id' => NULL, 'useShortname' => FALSE),
      'file' => 'betgame_competition.pages.inc',
      'path' => $path_page,
    ),
    'betgame_competition_match_result' => array(
      'variables' => array('match' => NULL, 'showDetails' => TRUE),
      'file' => 'betgame_competition.pages.inc',
      'path' => $path_page,
    ),
    
    'betgame_competition_page_group' => array(
      'template' => 'betgame_competition_page_group',
      'variables' => array(),
      'file' => 'betgame_competition.pages.inc',
      'path' => $path_page,
    ),
    
    /*
     * ADMIN
     */
    
    'betgame_competition_admin_form_table' => array(
      'render element' => 'data',
      'file' => 'betgame_competition.admin.theme.inc',
      'path' => $path_admin,
    ),
    

    'betgame_competition_admin_form_matchs' => array(
      'render element' => 'data',
      'file' => 'betgame_competition.match.admin.inc',
      'path' => $path_admin,
    )
  );
}

function _betgame_competition_page_competition_title(Competition $c) {
  return t('@title', array('@title' => $c->getName()));
  
}

/**
 * Implements HOOK betgame_entity_delete()
 */
function betgame_competition_betgame_entity_delete($entityclass, array $entity_ids) {
  $f = 'onDelete' . $entityclass;
  if(method_exists(betgame_competition_controller(), $f)) {
    betgame_competition_controller()->$f($entity_ids);
  }
  
}

/**
 * Implements HOOK hook_betgame_entity_update()
 */
function betgame_competition_betgame_entity_update(IEntity $entity) {
  if ($entity instanceof MatchResult) {
    betgame_competition_controller()->onMatchResultUpdated($entity);
    
  }
}


/**
 * Get url of the current page.
 *
 * @param bool $absolute If TRUE return absolute url, else a relative to the base url.
 *
 * @return string Path
 */
function betgame_competition_currenturl($absolute = FALSE) {
  global $base_url, $base_path;

  $uri = current_path();
  $query = drupal_get_query_parameters();
  if (!empty($query)) {
    $uri .= '?' . drupal_http_build_query($query);
  }

  if($absolute) {
    $uri = $base_url . $base_path . $uri;
  }

  return $uri;
}

function _betgame_competition_select_gameday(Competition $competition) {
  $cache = &drupal_static(__FUNCTION__, array());
  if(!is_object($competition)) {
    return array();
  }
  if(!isset($cache[$competition->getId()])) {
    $gamedays = betgame_competition_dao()->findGamedays($competition->getId());
    foreach($gamedays as $gd) {
      $cache[$competition->getId()][$gd->getId()] = $gd->getName();
    }
  }
  return $cache[$competition->getId()];
  
}

function _betgame_competition_select_group(Competition $competition) {
  $cache = &drupal_static(__FUNCTION__, array());
  if(!is_object($competition)) {
    return array();
  }
  if(!isset($cache[$competition->getId()])) {
    $cache[$competition->getId()][] = t('<None>');
    $groups = betgame_competition_dao()->findGroups($competition->getId());
    foreach($groups as $g) {
      $cache[$competition->getId()][$g->getId()] = $g->getName();
    }
  }
  return $cache[$competition->getId()];

}

function _betgame_competition_select_team(Competition $competition) {
  $cache = &drupal_static(__FUNCTION__, array());
  if(!is_object($competition)) {
    return array();
  }
  if(!isset($cache[$competition->getId()])) {
    $cache[$competition->getId()][] = t('<None>');
    $teams = betgame_competition_dao()->findTeams($competition->getId());
    foreach($teams as $t) {
      $cache[$competition->getId()][$t->getId()] = $t->getName();
    }
  }
  return $cache[$competition->getId()];

}

function _betgame_competition_select_match(Competition $competition) {
  $cache = &drupal_static(__FUNCTION__, array());
  if(!is_object($competition)) {
    return array();
  }
  if(!isset($cache[$competition->getId()])) {
    $cache[$competition->getId()][] = t('<None>');
    $matches = betgame_competition_dao()->findMatchs($competition->getId());
    foreach($matches as $m) {
      $cache[$competition->getId()][$m->getId()] = $m->getGamenumber();
    }
  }
  return $cache[$competition->getId()];

}
